
email: your-email@example.com

baseurl: "/NaverstoreExcelEase"



title: NaverstoreExcelEase
description: Use it for Excel file combining

theme: jekyll-theme-hacker

github:
  repository_url: https://github.com/eyeben/NaverstoreExcelEase